### PR TITLE
🐛  prevent IPAM addresses from being assigned to multiple devices

### LINKED ISSUE #1829: IPAM with a two network template causes the IP to be associated on both networks
/kind bug

**What steps did you take and what happened:**
When using Node IPAM (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/node-ipam-demo.md) on a template with 2 Networks, it will assign the IP address on both cards.

# Case 1 - GlobalInClusterIPPool
Here's a demo manifest of IPAM and Template:

```
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: GlobalInClusterIPPool
metadata:
  name: ricardo-network
spec:
  subnet: 192.168.117.0/24
  start: 192.168.117.152
  end: 192.168.117.180
  gateway: 192.168.117.254
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: ricardo-network
  namespace: test-network2
spec:
  template:
    spec:
      cloneMode: fullClone
      diskGiB: 25
      memoryMiB: 8192
      folder: tests
      network:
        devices:
        - dhcp4: true
          networkName: IsolatedPG
          deviceName: ens192
        - dhcp4: false
          networkName: Mgmt
          deviceName: ens224
          addressesFromPools:
          - apiGroup: ipam.cluster.x-k8s.io
            kind: GlobalInClusterIPPool
            name: ricardo-network
      numCPUs: 2
      template: ubuntu-2004-kube-v1.25.7
      thumbprint: 4E:CC:B5:CB:34:32:43:62:DE:A7:DD:BE:1C:B8:49:2F:67:1F:17:24
```

And the generated cloudinit metadata will look like:
```
instance-id: "ricardo-network-9dvmk"
local-hostname: "ricardo-network-9dvmk"
wait-on-network:
  ipv4: true
  ipv6: false
network:
  version: 2
  ethernets:
    id0:
      match:
        macaddress: "00:50:56:ab:26:b7"
      set-name: "ens192"
      wakeonlan: true
      dhcp4: true
      dhcp6: false
      addresses:
      - "192.168.117.152/0"
      gateway4: "192.168.117.254"
    id1:
      match:
        macaddress: "00:50:56:ab:c6:ab"
      set-name: "ens224"
      wakeonlan: true
      addresses:
      - "192.168.117.152/0"
      gateway4: "192.168.117.254"
```

Here is the created VSphereVM object:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereVM
metadata:
  creationTimestamp: "2023-03-20T18:15:03Z"
  finalizers:
  - vspherevm.infrastructure.cluster.x-k8s.io
  generation: 1
  labels:
    cluster.x-k8s.io/cluster-name: ricardo-network
    cluster.x-k8s.io/control-plane: ""
  name: ricardo-network-vm9vw
  namespace: test-network2
  ownerReferences:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereMachine
    name: ricardo-network-lbq25
    uid: 485c652f-ebf4-4d43-8739-da184e7de888
  resourceVersion: "791148"
  uid: 941b3c73-1575-434c-a22f-6d4764e3a202
spec:
  bootstrapRef:
    apiVersion: v1
    kind: Secret
    name: ricardo-network-hkkds
    namespace: test-network2
  cloneMode: fullClone
  datacenter: '*'
  diskGiB: 25
  folder: tests
  memoryMiB: 8192
  network:
    devices:
    - deviceName: ens192
      dhcp4: true
      networkName: IsolatedPG
    - addressesFromPools:
      - apiGroup: ipam.cluster.x-k8s.io
        kind: GlobalInClusterIPPool
        name: ricardo-network
      deviceName: ens224
      networkName: Mgmt
  numCPUs: 2
  os: Linux
  server: myvc.local
  template: ubuntu-2004-kube-v1.25.7
  thumbprint: 4E:CC:B5:CB:34:32:43:62:DE:A7:DD:BE:1C:B8:49:2F:67:1F:17:24
```

# Case 2 - InClusterIPPool

```
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: ricardo-network
  namespace: test-network2
spec:
  subnet: 192.168.117.0/24
  start: 192.168.117.152
  end: 192.168.117.180
  gateway: 192.168.117.254
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: ricardo-network
  namespace: test-network2
spec:
  template:
    spec:
      cloneMode: fullClone
      diskGiB: 25
      memoryMiB: 8192
      folder: tests
      network:
        devices:
        - dhcp4: true
          networkName: IsolatedPG
          deviceName: ens192
        - dhcp4: false
          networkName: Mgmt
          deviceName: ens224
          addressesFromPools:
          - apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: ricardo-network
      numCPUs: 2
      template: ubuntu-2004-kube-v1.25.7
      thumbprint: 4E:CC:B5:CB:34:32:43:62:DE:A7:DD:BE:1C:B8:49:2F:67:1F:17:24
```

VsphereVM:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereVM
metadata:
  creationTimestamp: "2023-03-20T18:29:46Z"
  finalizers:
  - vspherevm.infrastructure.cluster.x-k8s.io
  generation: 2
  labels:
    cluster.x-k8s.io/cluster-name: ricardo-network
    cluster.x-k8s.io/control-plane: ""
  name: ricardo-network-p5hl7
  namespace: test-network2
  ownerReferences:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereMachine
    name: ricardo-network-rjwv8
    uid: ab3a4225-a8d4-4f64-8462-4656780023a7
  resourceVersion: "794965"
  uid: 6f507546-3738-43d9-ad58-71f93e22afde
spec:
  biosUUID: 422ba80c-a342-12e0-0f95-c1ea9c352394
  bootstrapRef:
    apiVersion: v1
    kind: Secret
    name: ricardo-network-qkz6k
    namespace: test-network2
  cloneMode: fullClone
  datacenter: '*'
  diskGiB: 25
  folder: tests
  memoryMiB: 8192
  network:
    devices:
    - deviceName: ens192
      dhcp4: true
      networkName: IsolatedPG
    - addressesFromPools:
      - apiGroup: ipam.cluster.x-k8s.io
        kind: InClusterIPPool
        name: ricardo-network
      deviceName: ens224
      networkName: Mgmt
  numCPUs: 2
  os: Linux
  server: myvc.local
  template: ubuntu-2004-kube-v1.25.7
  thumbprint: 4E:CC:B5:CB:34:32:43:62:DE:A7:DD:BE:1C:B8:49:2F:67:1F:17:24
status:
  addresses:
  - 192.168.117.152
  - 192.168.111.80
  - 192.168.117.152
  - 2620:124:6020:c303:0:a:0:11e
  - 2620:124:6020:c303:250:56ff:feab:7fb3
  cloneMode: fullClone
  conditions:
  - lastTransitionTime: "2023-03-20T18:31:20Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-03-20T18:30:31Z"
    status: "True"
    type: IPAddressClaimed
  - lastTransitionTime: "2023-03-20T18:29:46Z"
    status: "True"
    type: VCenterAvailable
  - lastTransitionTime: "2023-03-20T18:31:20Z"
    status: "True"
    type: VMProvisioned
  host: 10.186.14.185
  network:
  - connected: true
    ipAddrs:
    - 192.168.117.152
    - 192.168.111.80
    macAddr: 00:50:56:ab:41:08
    networkName: IsolatedPG
  - connected: true
    ipAddrs:
    - 192.168.117.152
    - 2620:124:6020:c303:0:a:0:11e
    - 2620:124:6020:c303:250:56ff:feab:7fb3
    macAddr: 00:50:56:ab:7f:b3
    networkName: Mgmt
  ready: true
```
Guestinfo.metadata (already decoded):
```
instance-id: "ricardo-network-p5hl7"
local-hostname: "ricardo-network-p5hl7"
wait-on-network:
  ipv4: true
  ipv6: false
network:
  version: 2
  ethernets:
    id0:
      match:
        macaddress: "00:50:56:ab:41:08"
      set-name: "ens192"
      wakeonlan: true
      dhcp4: true
      dhcp6: false
      addresses:
      - "192.168.117.152/24"
      gateway4: "192.168.117.254"
    id1:
      match:
        macaddress: "00:50:56:ab:7f:b3"
      set-name: "ens224"
      wakeonlan: true
      addresses:
      - "192.168.117.152/24"
      gateway4: "192.168.117.254"
```

From there I can see:
* Wrong Netmask on the addresses when using GlobalInClusterIPPool
* The address being associated on both networks

**What did you expect to happen:**
Allocated IP address being assigned just on network ens224

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: v1.5.3
- Kubernetes version: (use `kubectl version`): v1.25.7 
- OS (e.g. from `/etc/os-release`): Ubuntu 22.10 as the KinD mgmt cluster

### PR DESCRIPTION
**Pull request by adobley**
**What this PR does / why we need it**:
We had previously made an assumption that the VSphereVM.Spec.Network.Devices[*].MACAddr would be set. This caused us to generate IPAMState that could be keyed on an empty string and later read for every device without a MACAddr set.

We now rely on the NetworkStatus as the source of truth for MACAddr to key and later retrieve the correct IPAM configuration for devices.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1829

**Special notes for your reviewer**:
This code feels excessively complex. I believe @srm09 is making some refactors in this repo and I don't want to clash with those changes, but this feels like it needs some rework. There are three objects, ctx.State.Network, ctx.IPAMState, and the ctx.VSphereVM.Spec.Network.Devices that all have a deep relationship. It feels dangerous to make changes and not potentially introduce a bug. We have some good tests, but missed this one, for example, because we assumed that the MACAddr would be set on the Spec.Network.Devices and was safe to use as a key.

Happy to work on a refactor, always love cleaning up code. Looking to not interfere with any existing efforts in that realm, let us know how we can best coordinate.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Fix #1829 - IPAM with a two network template causes the IP to be associated on both networks
```

### CODE REVIEW

**Comment by srm09** [comment]
This needs a rebase but am not sure any of these changes need to be moved over to the newer controller file at https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/vspherevm_ipaddress_reconciler_test.go

This should be ready for rework and possible merge once the rebase is done.

File: pkg/services/govmomi/ipam/status.go [hunk 1]
```diff
@@ -111,13 +111,17 @@ func BuildState(ctx context.VMContext) (map[string]infrav1.NetworkDeviceSpec, er
 // is returned, one for each device with addressesFromPools.
 // If any of the IPAddressClaims do not have an associated IPAddress yet,
 // a custom error is returned.
-func buildIPAMDeviceConfigs(ctx context.VMContext) ([]ipamDeviceConfig, error) {
+func buildIPAMDeviceConfigs(ctx context.VMContext, networkStatus []infrav1.NetworkStatus) ([]ipamDeviceConfig, error) {
 	boundClaims, totalClaims := 0, 0
 	ipamDeviceConfigs := []ipamDeviceConfig{}
 	for devIdx, networkSpecDevice := range ctx.VSphereVM.Spec.Network.Devices {
+		if len(networkStatus) == 0 || networkStatus[devIdx].MACAddr == "" {
```
Comment (srm09) [inline pkg/services/govmomi/ipam/status.go:118]:
```suggestion
		if len(networkStatus) == 0 ||
			len(networkStatus) <= devIdx ||
			networkStatus[devIdx].MACAddr == "" {
```

File: pkg/services/govmomi/ipam/status.go [hunk 2]
```diff
@@ -111,13 +111,17 @@ func BuildState(ctx context.VMContext) (map[string]infrav1.NetworkDeviceSpec, er
...
+			return ipamDeviceConfigs, errors.New("Waiting for devices to have MAC address set")
```
Comment (srm09) [inline pkg/services/govmomi/ipam/status.go:119]:
```suggestion
			return ipamDeviceConfigs, errors.New("waiting for devices to have MAC address set")
```

File: pkg/services/govmomi/ipam/status_test.go [hunk 3]
```diff
@@ -37,12 +39,16 @@ var (
 
 func Test_buildIPAMDeviceConfigs(t *testing.T) {
 	var ctx context.VMContext
+	var networkStatus []infrav1.NetworkStatus
 	var claim1, claim2, claim3 *ipamv1a1.IPAddressClaim
 	var address1, address2, address3 *ipamv1a1.IPAddress
 	var g *gomega.WithT
```
Comment (srm09) [inline pkg/services/govmomi/ipam/status_test.go:45]:
```suggestion
	var (
		ctx context.VMContext
		networkStatus []infrav1.NetworkStatus
		claim1, claim2, claim3 *ipamv1a1.IPAddressClaim
		address1, address2, address3 *ipamv1a1.IPAddress
		g *gomega.WithT
	)
```

File: pkg/services/govmomi/ipam/status_test.go [hunk 4]
```diff
@@ -205,20 +211,41 @@ func Test_buildIPAMDeviceConfigs(t *testing.T) {
...
 		g.Expect(config[0].IPAMAddresses).To(gomega.HaveLen(0))
 	})
 }
 
 func Test_BuildState(t *testing.T) {
 	var ctx context.VMContext
+	var networkStatus []infrav1.NetworkStatus
 	var claim1, claim2, claim3 *ipamv1a1.IPAddressClaim
 	var address1, address2, address3 *ipamv1a1.IPAddress
 	var g *gomega.WithT
```
Comment (srm09) [inline pkg/services/govmomi/ipam/status_test.go:225]: Same as above.

**Review by srm09 — COMMENTED** [review]
minor nits, otherwise /lgtm

**Comment by adobley** [comment]
@srm09 We updated the PR with your suggestions, thanks!

**Comment by srm09** [comment]
Could you make sure to run the unit/integration test suite locally to confirm there are no failures? I see the `test` job failing above.
