### PR TITLE
🐛  Adds default resource pool logic for cluster module creation

### LINKED ISSUE #1640: Cluster creation fails when no resource pool is specified
/kind bug

**What steps did you take and what happened:**
- Enable the node anti affinity feature for the CAPV deployment
- Create a cluster with the KCP and the MD objects using `VSphereMachineTemplate` objects without a resource pool, set `VSPHERE_RESOURCE_POOL` to `''` 
- Cluster creation fails since the `VSphereCluster` object never moves to `Ready` state.

**What did you expect to happen:**
- Cluster creation should succeed since resource pool is an optional field for `VSphereMachineTemplate` CR.

**Anything else you would like to add:**
Similar to the clone operation, if no resource pool is specified, then the resource pool lookup should fallback to the default value.

**Environment:**

- Cluster-api-provider-vsphere version: v1.4.0

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
This patch adds the logic to fall back to the default resource pool, if no resource pool is specified, during cluster module creation. It also checks whether the resource pool is owned by a compute cluster or a standalone host. In case of the owner being a standalone host, a warning is introduced on the VSphereCluster object and the cluster creation proceeds.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1640

**Special notes for your reviewer**:

**Release note**:

```release-note
Adds default resource pool logic for cluster module creation
```

### CODE REVIEW

File: controllers/clustermodule_reconciler.go [hunk 1]
```diff
@@ -253,3 +253,29 @@ func (r Reconciler) fetchMachineOwnerObjects(ctx *context.ClusterContext) (map[s
...
+
+func generateClusterModuleErrorMessage(errList []clusterModError) string {
+	sb := strings.Builder{}
+	sb.WriteString("failed to create cluster modules for: ")
+
+	for _, e := range errList {
+		sb.WriteString(fmt.Sprintf("%s %s, ", e.name, e.err.Error()))
+	}
+	msg := sb.String()
+	return msg[:len(msg)-2]
```
Comment (yastij) [inline controllers/clustermodule_reconciler.go:280]: why is this len -2 ?

Comment (srm09) [reply controllers/clustermodule_reconciler.go:280]: Remove the trailing `, ` after the final object name and error
