### PR TITLE
let deletion go through when the folder of a VSphereVM doesn't exist

### LINKED ISSUE #1000: CAPV doesn't delete the resources when the VM Folder doesn't exist
/kind bug

**What steps did you take and what happened:**

When you provision a cluster with a wrong folder name, you won't be able to delete the resources on the management cluster unless you create that folder, then trigger a delete

**What did you expect to happen:**
CAPV should be able to delete the resources when the supplied folder doesn't exist

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**: This PR fixes a bug where the deletion flow of a `VSphereVM` is blocked if its folder doesn't exist.

**Which issue(s) this PR fixes**: Fixes #1000 

**Special notes for your reviewer**:

/assign @vincepri @fabriziopandini 

**Release note**:

```release-note
let deletion go through when the folder of a VSphereVM doesn't exist
```

### CODE REVIEW

File: pkg/services/govmomi/service.go [hunk 1]
```diff
@@ -159,7 +159,7 @@ func (vms *VMService) DestroyVM(ctx *context.VMContext) (infrav1.VirtualMachine,
 	if err != nil {
 		// If the VM's MoRef could not be found then the VM no longer exists. This
 		// is the desired state.
-		if isNotFound(err) {
+		if isNotFound(err) || isFolderNotFound(err) {
```
Comment (vincepri) [inline pkg/services/govmomi/service.go:162]: Do you want to try using https://golang.org/pkg/errors/#Is ?

Comment (vincepri) [reply pkg/services/govmomi/service.go:162]: Or https://godoc.org/github.com/pkg/errors#Is given that's the package we actually use

Comment (yastij) [reply pkg/services/govmomi/service.go:162]: @vincepri - I like this. can you raise an issue for this, I'd like to refactor the error handling to use it ?

**Comment by randomvariable** [comment]
can we follow up and document this behaviour, as i'm sure it's going to be one of those things people might end up doing in vcenter and then find surprising. 
/approve

leave @vincepri to do lgtm wrt to the errors question.

File: pkg/services/govmomi/service.go (hunk 1 above)
Comment (vincepri) [reply pkg/services/govmomi/service.go:162]: #1004
