### PR TITLE
🐛 Allow thumbprint update on VSphereVM

### LINKED ISSUE #1718: Changing vCenter thumbprint causes the VSphereMachine reconciliation to be blocked
/kind bug

**What steps did you take and what happened:**
VSphereMachine does not have thumbprint set in its spec.
User updates the VSphereCluster `spec.thumbprint` when the certificates of the vCenter instance are updated. 
The CAPV logs show the following error:
```
\E1130 22:35:46.992024       1 vspheremachine_controller.go:469] capv-controller-manager/vspheremachine-controller/default/cluster01-control-plane-gbp6q "msg"="failed to CreateOrUpdate VSphereVM" "error"="admission webhook \"validation.vspherevm.infrastructure.x-k8s.io\" denied the request: VSphereVM.infrastructure.cluster.x-k8s.io \"cluster01-control-plane-shbbv\" is invalid: spec: Forbidden: cannot be modified"  "name"="cluster01-control-plane-shbbv" "namespace"="default"
E1130 22:35:46.992515       1 controller.go:317] controller/vspheremachine "msg"="Reconciler error" "error"="admission webhook \"validation.vspherevm.infrastructure.x-k8s.io\" denied the request: VSphereVM.infrastructure.cluster.x-k8s.io \"cluster01-control-plane-shbbv\" is invalid: spec: Forbidden: cannot be modified" "name"="cluster01-control-plane-gbp6q" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="VSphereMachine"
```

**What did you expect to happen:**
Changing the thumbprint on the VSphereCluster object should not cause the VSphereMachine reconciliation to be blocked.

**Anything else you would like to add:**
When a thumbprint of the vCenter is updated, the VSphereVM object would not report an error since the controller would use a valid cached session (with the updated thumbprint, mostly because the vspherecluster controller must have created a new one with the new thumbprint). This masks the stale value on the VSphereVM object's `spec`.

We should relax the webhook validation to allow for VSphereVM's thumbprint to be updated.
- For the case where the VSphereVM uses the thumbprint from the VSphereCluster object, the VSphereVM object would be updated with the correct value of the thumbprint.  
- For the case wherein the VSphereVM object has the thumbprint set, the VSphereVM object would continue to have the incorrect value. If the thumbprint was set on the `VSphereMachineTemplate` object used to create the VSphereMachine and VSphereVM objects, it is the responsibility of the user to update the thumbprint by creating a new object with the updated thumbprint. 

When we holistically think about the set off steps to follow when updating the thumbprint of a VSphereCluster, the user updates the VSphereCluster value and all the VSphereVM objects (residing on the vCenter which has updated thumbprint) get updated irrespective of the fact whether they have `spec.thumbprint` set or not.

**Ignore this** 
For the second case above, we should also think about checking for the vCenter URLs on the VSphereVM and the VSphereCluster object, and if they are the same consider updating the thumbprint value of the VSphereVM object.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by zhanggbj**
**What this PR does / why we need it**:
Updating thumbprint of VSphereCluster will cause reconcilererror for VSphereVM, to fix it
    - Relax the VSphereVM webhook to allow the thumbprint update.
    - Keep VSphereVM thumbprint consistent with VSphereCluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1718

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Allow thumbprint update on VSphereVM
```

### CODE REVIEW

File: pkg/services/vimmachine.go [hunk 1]
```diff
@@ -390,7 +390,10 @@ func (v *VimMachineService) createOrPatchVSphereVM(ctx *context.VIMMachineContex
 		if vm.Spec.Server == "" {
 			vm.Spec.Server = ctx.VSphereCluster.Spec.Server
 		}
-		if vm.Spec.Thumbprint == "" {
+		// Need to cover two cases:
+		// 1. vm.Spec.Thumbprint is empty after copy from VSphereMachine.Spec
+		// 2. VSphereCluster.Spec.Thumbprint is updated by user, such as when the certificates of the vCenter instance are updated
+		if vm.Spec.Thumbprint == "" || vm.Spec.Thumbprint != ctx.VSphereCluster.Spec.Thumbprint {
```
Comment (srm09) [inline pkg/services/vimmachine.go:396]: IMO this change is not necessary, but am open to listen to your thoughts here.
A bit of background, the `mutateFn` defined on line 340 aims to recreate a new copy of the `VSphereVM` object using the same values it originally used to create the `VSphereVM` object. This object is then passed to `patchOrCreate` which (in this case) updates the object stored in the API server.
So the check (on line 393, referring to the original file before the PR) is going to be true if the `VSphereMachine.Spec.thumbprint` is empty. If that is the case, then copy the value from the `VSphereCluster.Spec.thumbprint` into the VSphereVM object. 
Once the call to `patchOrCreate` is finished, you will see the VSphereVM object get updated with the newer thumbprint value.

File: apis/v1beta1/vspherevm_webhook.go [hunk 2]
```diff
@@ -107,6 +107,10 @@ func (r *VSphereVM) ValidateUpdate(old runtime.Object) error {
 		delete(newVSphereVMSpec, "os")
 	}
 
+	// allow changes to thumbprint
+	delete(oldVSphereVMSpec, "thumbprint")
+	delete(newVSphereVMSpec, "thumbprint")
```
Comment (srm09) [inline apis/v1beta1/vspherevm_webhook.go:112]: Since we have the same `delete` call being repeated over and over, consider creating a separate method which takes in a spec and a key and removes it from the spec map. List the keys which are allowed updates in an array and for each one pass it to this new function.

Comment (zhanggbj) [reply apis/v1beta1/vspherevm_webhook.go:112]: Sure, I can refine them in next patch.

File: pkg/services/vimmachine.go (hunk 1 above)
Comment (zhanggbj) [reply pkg/services/vimmachine.go:396]: Hi @srm09,
I'm totally agree with you about the case you mentioned, VSphereVM thumbprint is empty here so everything works fine with original logic.

I have a concern for another case, that user also specified thumbprint in VSphereMachineTemplate, so `VSphereMachine.Spec.thumbprint` has an old thumbprint, when user want to update VSphereCluster and VSphereVM with new thumbprint, according to [Line 337 ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/services/vimmachine.go#L377) , `vm.Spec.Thumbprint` will deep copy from `VSphereMachine.Spec.thumbprint` with old thumbprint, so it is not empty and the check is fail, I'm afraid it never get the chance to update with new thumbprint. What do you think?

Comment (srm09) [reply pkg/services/vimmachine.go:396]: For the case when the user is consuming the thumbprint via the VSphereMachineTemplate, the way to move forward with the update is to create a new template with the updated thumbprint value and use that for machine creation.

Comment (srm09) [reply pkg/services/vimmachine.go:396]: This PR should handle the case when thumbprint is not set on the `VSphereMachine.Spec`, and is consumed by the VSphereCluster object.

Comment (zhanggbj) [reply pkg/services/vimmachine.go]: As if `VSphereMachine.Spec.thumbprint` is not empty, user shouldn't use this approach (updating `VSphereCluster`)to update VSpherevm.Spec.Thumbprint, so original logic works fine. I'll revert the change. Thanks for the clarification!

**Comment by zhanggbj** [comment]
@srm09 All comments are addressed, would you please help to take another look, thanks!

/assign @srm09

**Comment by zhanggbj** [comment]
I assume pull-cluster-api-provider-vsphere-verify-gen error is not related to this PR.

**Comment by zhanggbj** [comment]
This PR is ready for a second review. Thanks!

**Comment by srm09** [comment]
/lgtm
@yastij PTAL

**Review by yastij — APPROVED** [review]
/approve

**Comment by samdulam** [comment]
I can't seem to be able to change thumbprint on a `vspherevm`. Editing the vspherevm accepts the new thumbprint but when inspecting again it has the old thumbprint.

**Comment by sbueringer** [comment]
Does the VSphereMachine also have a thumbprint field?

**Comment by samdulam** [comment]
> Does the corresponding VSphereMachine also have a thumbprint field set?

Yes.
I've changed the entry for vspherecluster but unable to change it on vspherevm.

This is causing my account to lockout in AD :(

**Comment by sbueringer** [comment]
Hm, I don't have the context on why that is forbidden

@chrischdi do you know?

**Comment by chrischdi** [comment]
> > Does the corresponding VSphereMachine also have a thumbprint field set?
> 
> Yes. Changing thumbprint on vspheremachine is forbidden?
> 
> I've changed the entry for vspherecluster but unable to change it on vspherevm.
> 
> This is causing my account to lockout in AD :(

This seem to be two separate issues.

A wrong thumbprint should lead to verification errors when trying to establish the client, but not lead to locking accounts in AD.

Could it be that in addition the vsphere credentials expired or are wrong?

**Comment by samdulam** [comment]
erros in capv-controller-manager
`Reconciler error failed to create vcenter session: failed to create client.... thumbprint does not match`
vcenter logs show login attempts from the IP address of the host where capv-controller is running.

I can confirm that the login works when its unlocked.

**Comment by samdulam** [comment]
How can I update thumbprint so I don't get verification errors please?

**Comment by samdulam** [comment]
@chrischdi 
Reconcile is working even though I occasionally see thumbprint mismatch messages in capv-controller pod. I've since updated all my vspherecluster objects.

I don't see a way to unset or update the thumbprint on vspheremachine object without creating a new vspheremachinetemplate. Is that the expectation?
