### PR TITLE
🐛 Adds ESXi host info label validation and sanitization logic

### LINKED ISSUE #1674: Cluster creation fails when using invalid label values for ESXi host info
/kind bug

**What steps did you take and what happened:**
1. In the vCenter instance, configure the ESXi hosts to have an IPv6 address as the primary address.
2. Create a cluster with 1 control plane and 1 worker nodes
3. Cluster creation fails with the following errors in the logs:
```
E1031 17:21:43.140137       1 vspheremachine_controller.go:331] capv-controller-manager/vspheremachine-controller "msg"="failed to patch machine with host info label" "error"="Machine.cluster.x-k8s.io \"mgmt-vc-control-plane-27f4d\" is invalid: metadata.labels: Invalid value: \"2620:124:6020:c003:0:69ff:fe2b:3763\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"  "machine "="mgmt-vc-control-plane-27f4d"
E1031 17:21:43.140980       1 controller.go:317] controller/vspheremachine "msg"="Reconciler error" "error"="Machine.cluster.x-k8s.io \"mgmt-vc-control-plane-27f4d\" is invalid: metadata.labels: Invalid value: \"2620:124:6020:c003:0:69ff:fe2b:3763\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" "name"="mgmt-vc-control-plane-q5kzq" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="VSphereMachine"
``` 

**What did you expect to happen:**
Cluster creation proceeds without any errors.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v1.4.1

/assign

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
This patch sanitizes the labels to be set on the Machine object to be conformant to the label value guidelines set in the k8s official docs. It also adds a validation to check if the sanitized label is conformant using the library functions from the apimachinery.

**Which issue(s) this PR fixes**:
Fixes #1674

**Special notes for your reviewer**:
With the anti affinity feature, we also included the logic to propagate ESXi host info to the CAPI Machine object which then gets transferred over to the k8s nodes. Since, the ESXi host information is added as a label, it should follow the label value  conventions set by the k8s docs.

**Release note**:
```release-note
Adds ESXi host info label validation and sanitization logic
```

### CODE REVIEW

File: pkg/util/label.go [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+// https://k8s.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
+//
+// The expected inputs for the object are IP addresses or FQDNs of the ESXi hosts.
+func SanitizeHostInfoLabel(info string) string {
+	updatedInfo := stripZoneInfo(info)
+	ip := net.ParseIP(updatedInfo)
+	if ip != nil {
+		if ipv4 := ip.To4(); ipv4 == nil {
+			// case when it is an IPv6 address
+			return fmt.Sprintf("%s.ipv6-literal", strings.ReplaceAll(updatedInfo, ":", "-"))
```
Comment (zjs) [inline pkg/util/label.go:38]: **nitpick**: Maybe include a comment explaining that this would be at most `8 * 4 (address) + 7 (dashess) + 12 (suffix) = 51` characters? (Mostly to make the thought process explicit in case there's some case in which it's not true.)

**Review by zjs — APPROVED** [review]
Looks good to me. Thank you for the quick fix!

File: controllers/vspheremachine_controller.go [hunk 2]
```diff
@@ -345,14 +348,22 @@ func (r *machineReconciler) patchMachineLabelsWithHostInfo(ctx context.MachineCo
...
+
 	machine := ctx.GetMachine()
 	patchHelper, err := patch.NewHelper(machine, r.Client)
 	if err != nil {
 		return err
 	}
 
 	labels := machine.GetLabels()
-	labels[constants.ESXiHostInfoLabel] = hostInfo
+	labels[constants.ESXiHostInfoLabel] = info
```
Comment (adam-jian-zhang) [inline controllers/vspheremachine_controller.go:366]: Will truncate the host info label affect anti-affinity logic? For example, if after sanitize, the hostInfoLabel are the same for two esxi hosts, will it affect our anti-affinity logic?
Another question, if DRS kick in, the VMs is vMotioned to another host, will this label get updated accordingly?

File: pkg/util/label.go [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+// https://k8s.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
+//
+// The expected inputs for the object are IP addresses or FQDNs of the ESXi hosts.
+func SanitizeHostInfoLabel(info string) string {
+	updatedInfo := stripZoneInfo(info)
+	ip := net.ParseIP(updatedInfo)
+	if ip != nil {
+		if ipv4 := ip.To4(); ipv4 == nil {
+			// In case of an IPv6 address, replace `:` with the acceptable `-` character.
+			// The size for the string would never exceed 51 (8 * 4 (address) + 7 (dashes) + 12 (suffix) = 51) characters.
```
Comment (sbueringer) [inline pkg/util/label.go:38]:
```suggestion
			// The size for the string would never exceed 52 (8 * 4 (address) + 7 (dashes) + 13 (suffix) = 52) characters.
```
nit: I think you missed the dot of the suffix

File: pkg/util/label.go [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+// TODO (srm09): consider removing it in the future.
+func stripZoneInfo(info string) string {
+	idx := strings.LastIndex(info, "%")
+	if idx == -1 {
+		return info
+	}
+	return info[:idx]
+}
+
+func sanitizeLabelLength(inputURL string) string {
```
Comment (sbueringer) [inline pkg/util/label.go:58]: nit: maybe add a comment to describe the sanitize logic
(I wonder if a func name like truncateLabel would fit better)

File: pkg/util/label_test.go [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+			input:    "foo-1.bar.com",
+			expected: "foo-1.bar.com",
+		},
+		{
+			name:     "for DNS entry with 63 characters",
+			input:    "esx13-r09.p01.1d91f0ee4f14b7e83bd42.australiaeast.avs.belch.com",
+			expected: "esx13-r09.p01.1d91f0ee4f14b7e83bd42.australiaeast.avs.belch.com",
+		},
+		{
+			name:     "for DNS entry with > 63 characters",
```
Comment (sbueringer) [inline pkg/util/label_test.go:79]: Maybe add other test cases where:
* multiple DNS segments have to be dropped
* dropping a DNS segment results in exactly 63 characters

**Review by sbueringer — COMMENTED** [review]
Just some nits.

I don't have enough context to assess the implications, only did a basic code review

File: controllers/vspheremachine_controller.go (hunk 2 above)
Comment (srm09) [reply controllers/vspheremachine_controller.go:366]: Nope, the anti affinity logic is independent of the label. The logic is to get the host info from the VM and add it as a label to the Machine object. Eventually, on the next reconcile, the label on the Machine object will be updated to display the latest info.

File: pkg/util/label.go (hunk 4 above)
Comment (srm09) [reply pkg/util/label.go:58]: Updated the function name, makes more sense that way.

File: pkg/util/label.go (hunk 3 above)
Comment (srm09) [reply pkg/util/label.go:38]: Updated.

File: pkg/util/label_test.go (hunk 5 above)
Comment (srm09) [reply pkg/util/label_test.go:79]: Done
