### PR TITLE
🐛 Delete legacy finalizer, fix setting ownerRef for `VSphereClusterIdentity `

### LINKED ISSUE #1482: Fix `v1alpha3` -> `v1beta1` upgrade workflow for `VSphereClusterIdentity`
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Upgraded `v1alpha3` cluster to `v1beta1`. Noticed that the identity secret has different finalizers being set in both the versions - 
`v1alpha3` sets `identity/infrastructure.cluster.x-k8s.io` while `v1beta1` sets `vspherecluster/infrastructure.cluster.x-k8s.io`

This issue is to fix the following - 
1. Add a fix to remove the previously set finalizer. Without this, the cluster deletion is not successful
2. Check for only the group and kind, and not the apiVersion, when setting ownerReferences on the secret
3. Remove secret deletion from the vspherecluster reconciler deletion loop since the secret should automatically get deleted successfully once the finalizers are removed and the cluster is deleted

**What did you expect to happen:**
The workload cluster should get deleted successfully after upgrading the cluster from `v1alpha3` to `v1alpha4`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v1.1.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by aartij17**
**What this PR does / why we need it**:
This PR does this following - 
- Check if the older VSphereClusterIdentity is present and delete it during the reconcileDelete phase. This is to make sure that clusters upgraded from v1alpha3 to v1alpha4/v1beta1 can be deleted once the finalizers are removed
- Check only the group and kind(and not the version) while setting ownerRef on VSphereClusterIdentity
- Remove explicit secret deletion from VSphereClusterReconciler (this already happens during the delete reconcile loop of VSphereClusterIdentity)

**Which issue(s) this PR fixes**:
Fixes #1482

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: controllers/vspherecluster_reconciler.go [hunk 1]
```diff
@@ -48,6 +48,8 @@ import (
 	infrautilv1 "sigs.k8s.io/cluster-api-provider-vsphere/pkg/util"
 )
 
+const legacyIdentityFinalizer string = "identity/infrastructure.cluster.x-k8s.io"
```
Comment (srm09) [inline controllers/vspherecluster_reconciler.go:51]: Do add an explicit comment marking it as Deprecated, kept only for upgrade issues.

File: controllers/vspherecluster_reconciler.go [hunk 2]
```diff
@@ -256,11 +262,9 @@ func (r clusterReconciler) reconcileIdentitySecret(ctx *context.ClusterContext)
 		}
 
 		// check if cluster is already an owner
-		if !clusterutilv1.IsOwnedByObject(secret, vsphereCluster) {
-			if len(secret.GetOwnerReferences()) > 0 {
-				return fmt.Errorf("another cluster has set the OwnerRef for secret: %s/%s", secret.Namespace, secret.Name)
```
Comment (srm09) [inline controllers/vspherecluster_reconciler.go:261]: Well I think we need to have the check that this secret is owned by a particular vSphereCluster object only? If this secret owned by another VSphereCluster, then we should throw an error.

**Review by srm09 — CHANGES_REQUESTED** [review]

File: controllers/vspherecluster_reconciler.go [hunk 3]
```diff
@@ -260,7 +270,10 @@ func (r clusterReconciler) reconcileIdentitySecret(ctx *context.ClusterContext)
 			if len(secret.GetOwnerReferences()) > 0 {
 				return fmt.Errorf("another cluster has set the OwnerRef for secret: %s/%s", secret.Namespace, secret.Name)
 			}
-
+		}
+		// check only the group and the kind of the ownerRef
+		if !clusterutilv1.HasOwner(secret.OwnerReferences, clusterv1.GroupVersion.String(),
```
Comment (yastij) [inline controllers/vspherecluster_reconciler.go:275]: why do we have this here? Isn't the check above sufficient?

**Review by yastij — COMMENTED** [review]
/approve
