### PR TITLE
respect the paused field and annotations

### LINKED ISSUE #783: Control-Plane-Node getting power off during `clusterctl move` operation
/kind bug

**What steps did you take and what happened:**
When I try to move clusterapi objects from capv cluster to temporary created kind cluster, ControlPlane VM for the cluster is getting powered off and move operation is failing.

Steps:
1. Provision capv cluster (`cluster-1`) with the help of temporary kind cluster(`temp-cluster-1`)
2. Move clusterapi objects for the `cluster-1`, from `temp-cluster-1` to `cluster-1` itself. and Delete temp-cluster-1 (Now, `cluster-1` is managing itself) [Successful move]
3. Create another temporary kind cluster (temp-cluster-2)
4. Move clusterapi objects for the `cluster-1`, from `cluster-1` to `temp-cluster-2` [failed]

During step 4, the cluster-1's control-plane vm is getting powered off during move operation.

**What did you expect to happen:**
Step 4 should have been successful and clusterapi object should have moved to `temp-cluster-2`.

**Anything else you would like to add:**
Also verified the status of `cluster` object which we are moving and it has the `paused: true` flag applied. Looks like capv is not respecting `paused` state during move properly.

Adding logs for cap, capv, clusterctl_move.
[capi.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4258604/capi.log)
[capv.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4258605/capv.log)
[clusterctl_move.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4258606/clusterctl_move.log)

```
NAMESPACE    NAME                                                    PHASE
default   cluster.cluster.x-k8s.io/test-0226-management-cluster   Provisioned
```

Note: As the cluster is managing itself when move operation was performed, once the controlplane vm is powered off. No logs are retrived.

**Environment:**

- Cluster-api-provider-vsphere version: 0.5.5
- Kubernetes version: (use `kubectl version`): 1.16.2 (producible on any version)

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** : Fixes #783

**Special notes for your reviewer**:

/assign @detiber 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
do not reconcile resources if cluster.spec.Paused is true
```

### CODE REVIEW

**Comment by detiber** [comment]
@yastij at a quick glance, lgtm. Are there already watches in place for the Cluster resource in each of these controllers so that a change from paused = true to paused=false would trigger a reconciliation for the resources?

The following PR against cluster-api adds a watch with predicates to only reconcile if the paused field was changed on the Cluster: https://github.com/kubernetes-sigs/cluster-api/pull/2432

File: controllers/vspheremachine_controller.go [hunk 1]
```diff
@@ -95,7 +100,33 @@ func AddMachineControllerToManager(ctx *context.ControllerManagerContext, mgr ma
...
+				if _, ok := e.Meta.GetAnnotations()[clusterv1.PausedAnnotation]; !ok {
+					return false
+				}
+				return true
+			},
+		})
+	if err != nil {
+		return err
+	}
+	return nil
```
Comment (detiber) [inline controllers/vspheremachine_controller.go]: Will probably need something similar to this for the other types as well.

File: controllers/vspherecluster_controller.go [hunk 2]
```diff
@@ -339,9 +345,9 @@ func (r clusterReconciler) reconcileLoadBalancer(ctx *context.ClusterContext) (b
 			"load-balancer-gvk", loadBalancer.GroupVersionKind().String(),
 			"load-balancer-namespace", loadBalancer.GetNamespace(),
 			"load-balancer-name", loadBalancer.GetName(),
-			"cluster-gvk", ctx.Cluster.GroupVersionKind().String(),
-			"cluster-namespace", ctx.Cluster.GetNamespace(),
-			"cluster-name", ctx.Cluster.GetName())
+			"vspherecluster-gvk", ctx.VSphereCluster.GroupVersionKind().String(),
+			"vspherecluster-namespace", ctx.VSphereCluster.GetNamespace(),
+			"vspherecluster-name", ctx.VSphereCluster.GetName())
```
[the remark this answers is not in the document]
Comment (yastij) [reply controllers/vspherecluster_controller.go]: will do in a followup

File: controllers/vspherecluster_controller.go [hunk 3]
```diff
@@ -856,40 +862,21 @@ func (r clusterReconciler) loadBalancerToCluster(o handler.MapObject) []ctrl.Req
 		return nil
 	}
 
-	var clusterRef *metav1.OwnerReference
+	var vsphereClusterRef *metav1.OwnerReference
 	for _, ownerRef := range obj.GetOwnerReferences() {
 		if ownerRef.APIVersion == clusterv1.GroupVersion.String() &&
```
[the remark this answers is not in the document]
Comment (yastij) [reply controllers/vspherecluster_controller.go]: will do in a followup PR

File: Makefile [hunk 4]
```diff
@@ -57,6 +57,7 @@ GC_KIND ?= true
 RELEASE_DIR := out
 BUILD_DIR := .build
 OVERRIDES_DIR := $(HOME)/.cluster-api/overrides/infrastructure-vsphere/$(VERSION)
+E2E_ARGS := --e2e.sshAuthKey="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCbQg7ywSD1oJAwAHhQuemrL6C9wvOIgE7wfZ0PfqolcTEQbLbv7Zxe1/TRzr4B20pb6GMryJ7O3SH9kuCubDYQ4Atw9MF/iAtsg0s3Xs4a3RAqoeaTHA0u401Um27ANDVqLswdTZ0J0Ev+XqRCEgPX+IpGgiNOyiHxfIgwdev/fG1MmMEyCKj8JNlRghFnleBcE+N3Mu0rKb88ascch2mKLY5fGDwbnC3V7d6LE6jWVT5HV391N4IWmjoBjlBt3mfzNslWqJUS+PxRbYR3i7vyVrpb/mkw1YG1jeomTAmkx4kwiV7hSzNVF6pKNIOoB1mpwULJ0VL+UkM8IPEfVJb root@9ae81f510a14"
```
Comment (ncdc) [inline Makefile]: ?

Comment (yastij) [reply Makefile]: @ncdc - I'm adding an ssh key to retrieve cloud-init logs etc.., there are some failures where the cluster is stuck in provisioning state

**Comment by detiber** [comment]
lgtm pending resolution on @ncdc's comment

File: controllers/vspheremachine_controller.go [hunk 5]
```diff
@@ -507,3 +543,21 @@ func (r machineReconciler) reconcileReadyState(ctx *context.MachineContext, vm *
 	ctx.VSphereMachine.Status.Ready = true
 	return true, nil
 }
+
+func (r *machineReconciler) reconcileRequests(a handler.MapObject) []reconcile.Request {
```
Comment (ncdc) [inline controllers/vspheremachine_controller.go]: clusterToVSphereMachines?

**Comment by ncdc** [comment]
/lgtm
/hold

Feel free to remove the hold if you want to merge as-is - my comments are just about renaming the map functions to have clearer names and aren't required but would be nice to have for the sake of clarity.

File: controllers/haproxyloadbalancer_controller.go [hunk 6]
```diff
@@ -778,3 +798,29 @@ func (r haproxylbReconciler) controlPlaneMachineToHAProxyLoadBalancer(o handler.
...
+			map[string]string{
+				clusterv1.ClusterLabelName: a.Meta.GetName(),
+			},
+		))
+	if err != nil {
+		return requests
+	}
+	for _, lb := range lbs.Items {
+		r := reconcile.Request{
+			NamespacedName: apitypes.NamespacedName{
```
Comment (ncdc) [inline controllers/haproxyloadbalancer_controller.go]: No need to change but just as an FYI for the future, CAPI now has `util.ObjectKey()` that you can use to get this, instead of typing it out.

File: controllers/vspherevm_controller.go [hunk 7]
```diff
@@ -223,6 +224,16 @@ func (r vmReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reterr error)
 		return r.reconcileDelete(vmContext)
 	}
 
+	cluster, err := clusterutilv1.GetClusterFromMetadata(r.ControllerContext, r.Client, vsphereVM.ObjectMeta)
```
Comment (ncdc) [inline controllers/vspherevm_controller.go]: Didn't we want to do this before calling either reconcileDelete or reconcileNormal? cc @vincepri

File: controllers/haproxyloadbalancer_controller.go [hunk 8]
```diff
@@ -204,7 +190,15 @@ func (r haproxylbReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reterr
 	if !haproxylb.ObjectMeta.DeletionTimestamp.IsZero() {
 		return r.reconcileDelete(ctx)
 	}
-
+	cluster, err := clusterutilv1.GetClusterFromMetadata(r.Context, r.Client, haproxylb.ObjectMeta)
```
Comment (ncdc) [inline controllers/haproxyloadbalancer_controller.go]: Same question about checking for paused before calling reconcileDelete

File: controllers/vspherevm_controller.go (hunk 7 above)
Comment (detiber) [reply controllers/vspherevm_controller.go]: We're likely going to have to be careful with that (not just here, but other places as well), otherwise we may end up in a situation where we can't delete a resource if the Cluster resource is not present.

Comment (yastij) [reply controllers/vspherevm_controller.go]: if we check for pause before the delete (and optionally go through and continue if we can't find the cluster) we can endup in `reconcileNormal` which needs the `Cluster` object. A solution could be to recheck for `err` before reconcile normal, wdyt @detiber @ncdc

File: controllers/haproxyloadbalancer_controller.go (hunk 6 above)
Comment (yastij) [reply controllers/haproxyloadbalancer_controller.go]: I'll add this to things to file out of this PR with @detiber 's comments

**Comment by ncdc** [comment]
@detiber WDYT?
