### PR TITLE
:bug: Fix nil pointer error in retrieveVcenterSession

### LINKED ISSUE #2302: CAPV controller panics if underlying VSphereVMs are deleted
/kind bug


After doing some manual deletions of VMs/ removing some finalizers on my cluster objects, i saw capv controller manager panicking...

```
Hi folks, I just (after doing some manual things in vsphere to delete some machiens) ,saw a panic ….
I0830 08:34:54.527424       1 reflector.go:257] Listing and watching *v1.Secret from pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169                                                                                                    
I0830 08:34:54.526331       1 controller.go:118] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="vspherevm" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="VSphereVM
" VSphereVM="default/windows-cluster-dt6bx-89h92" namespace="default" name="windows-cluster-dt6bx-89h92" reconcileID=e34e3a75-4b2f-4948-a143-1ad972e433ee                                                                                             
I0830 08:34:54.526551       1 controller.go:118] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="vspherevm" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="VSphereVM
" VSphereVM="default/windows-cluster-dt6bx-vw75j" namespace="default" name="windows-cluster-dt6bx-vw75j" reconcileID=7e9a7012-597c-48d3-9046-dcb8c91e08cd                                                                                             
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                                                                                                   
        panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1b6fbf6]                                                                                                                                                                              
                                                                                                                                                                                                                                                      
goroutine 759 [running]:                                                                                                                                                                                                                              
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()                                                                                                                                                                
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:119 +0x1fa                                                                                                                                           
panic({0x1e89580, 0x38a03b0})                                                                                                                                                                                                                         
        /usr/local/go/src/runtime/panic.go:884 +0x212                                                                                                                                                                                                 
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.retrieveVcenterSession({0xc000a0ba40?, {0x25e9a88?, 0x3911cb8?}}, {0x25f9a38, 0xc0009f4300}, 0xc000448380)                                                                          
        /workspace/controllers/vspherevm_controller.go:559 +0x296                                                                                                                                                                                     
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.Reconcile({0xc000a0ba40?, {0x25e9a88?, 0x3911cb8?}}, {0x25f9a38, 0xc0009f4300}, {{{0xc000a26d26, 0x7}, {0xc0006bc620, 0x1b}}})                                                      
        /workspace/controllers/vspherevm_controller.go:186 +0x34e                                                                                                                                                                                     
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x25f9a38?, {0x25f9a38?, 0xc0009f4300?}, {{{0xc000a26d26?, 0x1d7c900?}, {0xc0006bc620?, 0x0?}}})                                                                       
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122 +0xc8                                                                                                                                            
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005eaaa0, {0x25f9990, 0xc0009be200}, {0x1fb2c40?, 0xc0003f0b40?})                                                                                           
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323 +0x3a5                                                                                                                                           
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005eaaa0, {0x25f9990, 0xc0009be200})                                                                                                                     
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274 +0x1d9                                                                                                                                           
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                                                                                                                                  
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235 +0x85                                                                                                                                            
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2                                                                                                                                                           
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:231 +0x333
```
will add more details shortly...


**What steps did you take and what happened:**

Deleted some infra manually

**What did you expect to happen:**

CAPV would gracefully tolerate changes to missing objects and update its caches however it needs to, rather than panicking b/c things are gone.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Cluster-api-provider-vsphere version: v1.7.0_vmware.0                                                                                                                                            
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by killianmuldoon**
Fix a nilpointer error that can occur in the vSphereVM reconciler if the controller's infrastructureRef is nil.

Fixes #2302

### CODE REVIEW

File: controllers/vspherevm_controller.go [hunk 1]
```diff
@@ -569,6 +570,9 @@ func (r vmReconciler) retrieveVcenterSession(ctx goctx.Context, vsphereVM *infra
 			params)
 	}
 
+	if cluster.Spec.InfrastructureRef == nil {
```
Comment (killianmuldoon) [inline controllers/vspherevm_controller.go:573]: This is the minimal fix for this, which I think should be backported. Otherwise there's a bit of refactoring that could be done on this controller to do this earlier in the reconcile, but there's a few questions around what should happen when the cluster is paused, and how the controller reacts if it can't find the cluster. 

Currently it ignores errors when trying to retrieve the cluster and only changes behaviour if it can find the cluster and the cluster is paused.

Happy to do that on this PR, but I thought it might be more difficult to refactor changes like that - @sbueringer @chrischdi opinions?

Comment (chrischdi) [reply controllers/vspherevm_controller.go:573]: I think this one is good for backporting. If we want to do the improved: let's do that on top and separate it from this so we don't cherry-pick it back.

Comment (sbueringer) [reply controllers/vspherevm_controller.go:573]: Sounds good. Let's keep this PR as is

**Comment by sbueringer** [comment]
/lgtm
/approve

Panic's are annoying so cherry-picking this back all the way
