### PR TITLE
🌱 test: remove kube-vip cleanup 

### LINKED ISSUE #2584: v1.29 based tests are flaky, e.g. conformance
/kind bug

**What steps did you take and what happened:**

E.g. `periodic-conformance-main` is very [flaky](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-conformance-main) / failing.

Reason for it is (e.g. [this prowjob](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-conformance-main/1739998234052399104)):

* CAPI creates the workload cluster
* after `kubeadm init`, the `sed` which changes `super-admin.conf` to `admin.conf` causes a recreation of the kube-vip pod.
* things process fast and the kube-conformance tests start before the mirror-pod of kube-vip is up-to-date.
* conformance tests wait for all pods to be ready, but fails because the old kube-vip pod which still did exist at that time never gets Ready, but removed instead

The logs show that the pod it is waiting for is still the old one referring `super-admin.conf`.
The artifacts show that this pod does not exist anymore, but the new one exists, referring `admin.conf` and having a different uid.

**What did you expect to happen:**

Tests to succeed

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Removes the `kube-vip-cleanup.sh` script from templates.

The cleanup caused an additional recreation of the kube-vip pod and by that as side-effect, some tests to fail.

An alternative approach may be not doing an in-place sed, but creating a new file instead.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2584

### CODE REVIEW

File: packaging/flavorgen/flavors/kubevip/topology.go [hunk 1]
```diff
@@ -96,11 +96,11 @@ func TopologyPatch() clusterv1.ClusterClassPatch {
...
-			Op:        "add",
-			Path:      "/spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-",
-			ValueFrom: &clusterv1.JSONPatchValue{Template: ptr.To("/etc/kube-vip-cleanup.sh")},
-		},
+		// clusterv1.JSONPatch{
+		// 	Op:        "add",
+		// 	Path:      "/spec/template/spec/kubeadmConfigSpec/postKubeadmCommands/-",
+		// 	ValueFrom: &clusterv1.JSONPatchValue{Template: ptr.To("/etc/kube-vip-cleanup.sh")},
+		// },
 	)
```
Comment (zhanggbj) [inline packaging/flavorgen/flavors/kubevip/topology.go:104]: Hey @chrischdi ,

Are the commented code left intentionally? Otherwise, I think we could remove them :-)

**Review by zhanggbj — APPROVED** [review]
Jut a nit. 
/lgtm

File: packaging/flavorgen/flavors/kubevip/topology.go (hunk 1 above)
Comment (sbueringer) [reply packaging/flavorgen/flavors/kubevip/topology.go:99]: Good catch. I agree => deleted

**Comment by sbueringer** [comment]
/lgtm
/approve

@chrischdi Pleas take a quick look once you're back. But I'll merge now to get CI back to green / unblock other stuff

**Comment by chrischdi** [comment]
> /lgtm /approve
> 
> @chrischdi Pleas take a quick look once you're back. But I'll merge now to get CI back to green / unblock other stuff

Thanks for finishing this! 👍
