### PR TITLE
Use DataSecretName to get Bootstrap data

### LINKED ISSUE #923: Use dataSecretName instead of bootstrapRef to get userdata
/kind bug

**What steps did you take and what happened:**
I create a machine resource with `bootstrap.dataSecretName` set to my custom userdata secret. 

```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  name: dhawal-vm
spec:
  bootstrap:
    dataSecretName: dhawal-vm-updated
  clusterName: dhawal-vm
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereMachine
    name: dhawal-vm
  version: v1.17.3
status:
  bootstrapReady: true
```

The vsphere controller doesn't use that secret and throws the below error:
`E0603 05:41:08.419266       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile VM: failed to retrieve bootstrap data secret for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereVM capi-test/dhawal-vm: Secret \"\" not found"  "controller"="vspherevm" "request"={"Namespace":"capi-test","Name":"dhawal-vm"}`

**What did you expect to happen:**
I expect vsphere controller to read the secret from `bootstrap.dataSecretName` instead of `bootstrap.configRef.Name`
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/3e0ae86bed8f5b3fb9c2d7d9d80fc427115468c1/pkg/services/govmomi/service.go#L369-L372

**Anything else you would like to add:**
The aws provider gets the secret from `bootstrap.dataSecretName`:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/13ceee9bfe8ac582d0c4e71e9b74dfe387fddb62/pkg/cloud/scope/machine.go#L248

**Environment:**

- Cluster-api-provider-vsphere version: v0.6.4
- Kubernetes version: (use `kubectl version`): v1.17.3
- OS (e.g. from `/etc/os-release`): ubuntu 18.03

### PR DESCRIPTION
**Pull request by dhawal55**
**What this PR does / why we need it**:
Use DataSecretName to get Bootstrap (cloudinit) data

**Which issue(s) this PR fixes**:
Fixes #923

### CODE REVIEW

**Comment by yastij** [comment]
@dhawal55 - seems like you need to sign the cla + set your user + email on your git config

**Comment by dhawal55** [comment]
@yastij Thank you for approving the PR. I signed the cla and updated my gitlab account with my email. Is there any way to rerun the checks?

File: controllers/vspheremachine_controller.go [hunk 1]
```diff
@@ -388,7 +389,11 @@ func (r machineReconciler) reconcileNormalPre7(ctx *context.MachineContext) (run
 			}))
 
 		// Instruct the VSphereVM to use the CAPI bootstrap data resource.
-		vm.Spec.BootstrapRef = ctx.Machine.Spec.Bootstrap.ConfigRef
+		// TODO: BootstrapRef field should be replaced with BootstrapSecret of type string
+		vm.Spec.BootstrapRef = &corev1.ObjectReference{
+			Name:      *ctx.Machine.Spec.Bootstrap.DataSecretName,
```
Comment (yastij) [inline controllers/vspheremachine_controller.go:394]: what if the `DataSecretName` is nil ? the VM shouldn't have a `BootstrapRef` if the secret isn't available yet

Comment (dhawal55) [reply controllers/vspheremachine_controller.go:394]: @yastij Yes, I thought about it and wanted to add a nil check. But I realized that my changes are in `reconcileNormalPre7` function and and there is already a check for nil `DataSecretName` just befoe this function is called:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspheremachine_controller.go#L312-L318

Comment (yastij) [reply controllers/vspheremachine_controller.go:394]: oh that's all good then. 

I know it'll work like this as is, but can you add for completeness:
```
APIVersion: "v1",
Kind:       "Secret",
```

Comment (dhawal55) [reply controllers/vspheremachine_controller.go:394]: @yastij  I'm not sure what you are asking here. Do you want me to change the type for `BootstrapRef`?

Comment (yastij) [reply controllers/vspheremachine_controller.go:394]: @dhawal55 - we need the `APIVersion` and `Kind` fields of the `ObjectReference` set

Comment (dhawal55) [reply controllers/vspheremachine_controller.go]: @yastij Thank you. I updated the PR.
