### PR TITLE
🐛 ServiceAccount Controller: Forcefully set controller ownership on resources being reconciled

### LINKED ISSUE #1927: CAPV doesn't take ownership of existing resources its reconciling
### What steps did you take and what happened?

In vSphere 8, the API group of ProviderServiceAccount joined CAPV, but older clusters on vSphere 7 were using a different API group in a custom controller. This means reconciliation of providerserviceaccounts fail because CAPV is not the controller owner of resources it is trying to reconcile and errors out.

### What did you expect to happen?

CAPV reconciles providerserviceaccounts fully

### Cluster API version

N/A

### Kubernetes version

N/A

### Anything else you would like to add?

N.A

### Label(s) to be applied

/kind bug
/assign
/lifecycle active

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1927

As part of this, had to implement pause support for the integration tests.

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
CAPV forces setting controller ownership of resources reconciled by the Service Account controller, which may have stale references when upgrading from vSphere 7.
```

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
/approve

verify jobs are failing, can you fix them? otherwise lgtm

**Comment by randomvariable** [comment]
> verify jobs are failing, can you fix them? otherwise lgtm

accidentally deleted the wrong file, lol

File: pkg/util/supervisor.go [hunk 1]
```diff
@@ -34,3 +40,58 @@ func IsSupervisorType(input interface{}) (bool, error) {
...
+		Name:       owner.GetName(),
+	}
+
+	deleteAllControllers(controlled, ref)
+
+	return controllerutil.SetControllerReference(owner, controlled, scheme)
+}
+
+// deleteAllControllers Removes existing controller reference from controlled object.
+func deleteAllControllers(controlled metav1.Object, ref metav1.OwnerReference) {
```
Comment (srm09) [inline pkg/util/supervisor.go:73]:
```suggestion
func deleteAllControllerRefs(controlled metav1.Object, ref metav1.OwnerReference) {
```

File: pkg/util/supervisor.go [hunk 2]
```diff
@@ -34,3 +40,58 @@ func IsSupervisorType(input interface{}) (bool, error) {
...
+	owners := controlled.GetOwnerReferences()
+	for i := range owners {
+		if owners[i].Controller != nil && *owners[i].Controller && !referSameObject(owners[i], ref) {
```
Comment (srm09) [inline pkg/util/supervisor.go:76]: `!referSameObject(owners[i], ref)` is this check for the follow up reconcile loops for the same object? Can you add a comment about the same if that's the case.

**Review by srm09 — CHANGES_REQUESTED** [review]
Minor nits. Also, it'd be great if you could add an integration test for the same. Thanks :)

**Comment by srm09** [comment]
/retitle 🐛 ServiceAccount Controller: Forcefully set controller ownership on resources being reconciled
/lgtm
/approve
