### PR TITLE
Checks for length of network statuses while generating metadata

### LINKED ISSUE #1155: capv-controller-manager pod is in a crash loop
/kind bug

**What steps did you take and what happened:**
1. Create workload cluster with two devices
2. After workload cluster is deployed successfully, delete a device from VC
3. Step2 caused capv-controller-manager pod crash

```
goroutine 421 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1f37b60, 0xc0007f9380)
    /usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-vsphere/pkg/util.GetMachineMetadata(0xc000629be0, 0x19, 0x1ab7815, 0x9, 0xc000826120, 0x28, 0xc000629be0, 0x19, 0x0, 0x0, ...)
    /workspace/pkg/util/machines.go:147 +0x8b9
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).reconcileMetadata(0x3567598, 0xc000e4e180, 0x0, 0x0, 0xe)
    /workspace/pkg/services/govmomi/service.go:227 +0x102
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi.(*VMService).ReconcileVM(0x3567598, 0xc0008321e0, 0x20bf000, 0x29, 0xc00089cd00, 0x0, 0x0, 0xc000b67828, 0x1443a0e, 0xc0006d3110, ...)
    /workspace/pkg/services/govmomi/service.go:125 +0xa77
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.reconcileNormal(0xc000707a80, 0xc0008321e0, 0xc0001f3b80, 0xc0006d3100, 0xc000629be0, 0x19)
    /workspace/controllers/vspherevm_controller.go:326 +0x22f
sigs.k8s.io/cluster-api-provider-vsphere/controllers.vmReconciler.Reconcile(0xc000707a80, 0xc00058cfb0, 0x6, 0xc000629be0, 0x19, 0xc000912f00, 0x0, 0x0, 0x0)
    /workspace/controllers/vspherevm_controller.go:280 +0x783
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00013c630, 0x1de7780, 0xc00092d1a0, 0x354ec00)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:255 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00013c630, 0xc00056a900)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:231 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00013c630)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:210 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000928050)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000928050, 0x3b9aca00, 0x0, 0x1, 0xc00009a0c0)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000928050, 0x3b9aca00, 0xc00009a0c0)
    /go/pkg/mod/k8s.io/apimachinery@v0.17.9/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.14/pkg/internal/controller/controller.go:192 +0x468
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
Adds a check for the length of the network status before generating the metadata string

**Which issue(s) this PR fixes**:
Fixes #1155

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/hold

### CODE REVIEW

**Comment by srm09** [comment]
/retitle WIP: Checks for length of network status while generating metadata

File: pkg/util/machines.go [hunk 1]
```diff
@@ -140,12 +142,20 @@ func IsControlPlaneMachine(machine metav1.Object) bool {
 func GetMachineMetadata(hostname string, machine infrav1.VSphereVM, networkStatus ...infrav1.NetworkStatus) ([]byte, error) {
 	// Create a copy of the devices and add their MAC addresses from a network status.
 	devices := make([]infrav1.NetworkDeviceSpec, len(machine.Spec.Network.Devices))
+
+	// checking that the vSphere virtual machine's network status, if any
+	// match the number of network devices for the VSphereVM
+	if statuses := len(networkStatus); statuses > 0 {
+		if statuses != len(machine.Spec.Network.Devices) {
+			machine.Status.FailureMessage = pointer.StringPtr("Incorrect number of network devices. A network device was removed from the VM.")
```
Comment (yastij) [inline pkg/util/machines.go:150]: I don't think we should mark the machine as failed here. we should return a specific error and catch at the caller level.

File: pkg/util/machines.go [hunk 2]
```diff
@@ -140,12 +142,20 @@ func IsControlPlaneMachine(machine metav1.Object) bool {
...
+			machine.Status.FailureReason = capierrors.MachineStatusErrorPtr(capierrors.InvalidConfigurationMachineError)
```
Comment (yastij) [inline pkg/util/machines.go:151]: we shouldn't be setting `FailureMessage` and `FailureReason` on the machine directly. Those should be set at the `VSphereVM` level (our controllers will bubble it up to the `VSphereMachine` and CAPI will read from it)

Comment (srm09) [reply pkg/util/machines.go]: changed machine -> vsphereVM

**Comment by srm09** [comment]
@yastij Does it make sense to change the base branch to `main` and then backport it to `release-0.7` branch?

File: pkg/util/machines.go (hunk 2 above)
Comment (yastij) [reply pkg/util/machines.go]: thanks

**Comment by yastij** [comment]
@srm09 - ideally yes, also can you please address https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1156#discussion_r604122776 ? `GetMachineMetadata()` shouldn't have side-effects (`FailureMessage` and `FailureReason` should be set by the caller)

**Comment by srm09** [comment]
/retitle Checks for length of network statuses while generating metadata

File: pkg/util/machines.go [hunk 3]
```diff
@@ -164,14 +162,19 @@ func GetMachineMetadata(hostname string, machine infrav1.VSphereVM, networkStatu
...
 		}
-		if machine.Spec.Network.Devices[i].DHCP6 {
+		if vsphereVM.Spec.Network.Devices[i].DHCP6 {
 			waitForIPv6 = true
 		}
 	}
 
+	// Add the MAC Address to the network device
+	for i, status := range networkStatuses {
+		devices[i].MACAddr = status.MACAddr
```
Comment (yastij) [inline pkg/util/machines.go:175]: this also introduces the opposite issue: If someones adds a NIC manually, this would panic. `len(devices)` might be smaller than `len(networkStatuses)`

File: pkg/util/machines.go [hunk 4]
```diff
@@ -137,22 +137,20 @@ func IsControlPlaneMachine(machine metav1.Object) bool {
 
 // GetMachineMetadata returns the cloud-init metadata as a base-64 encoded
 // string for a given VSphereMachine.
-func GetMachineMetadata(hostname string, machine infrav1.VSphereVM, networkStatus ...infrav1.NetworkStatus) ([]byte, error) {
+func GetMachineMetadata(hostname string, vsphereVM infrav1.VSphereVM, networkStatuses ...infrav1.NetworkStatus) ([]byte, error) {
 	// Create a copy of the devices and add their MAC addresses from a network status.
-	devices := make([]infrav1.NetworkDeviceSpec, len(machine.Spec.Network.Devices))
+	devices := make([]infrav1.NetworkDeviceSpec, len(vsphereVM.Spec.Network.Devices))
```
Comment (yastij) [inline pkg/util/machines.go:142]: it should be the max of `len(vsphereVM.Spec.Network.Devices)` and `len(networkStatuses)`

File: pkg/services/govmomi/service.go [hunk 5]
```diff
@@ -224,6 +224,16 @@ func (vms *VMService) reconcileMetadata(ctx *virtualMachineContext) (bool, error
 		return false, err
 	}
 
+	// checking that the vsphereVM's network statuses, if any match the number of
+	// network devices for the VSphereVM
+	if statuses := len(ctx.State.Network); statuses > 0 {
+		if statuses != len(ctx.VSphereVM.Spec.Network.Devices) {
```
Comment (yastij) [inline pkg/services/govmomi/service.go:230]: Ideally, I'd like us to fail only when we remove a device. I don't want us to block additions, until we support things like `sr-iov`

Comment (srm09) [reply pkg/services/govmomi/service.go:230]: Adding a greater than check `>` should be sufficient in this case then.

File: pkg/util/machines.go [hunk 6]
```diff
@@ -135,24 +135,31 @@ func IsControlPlaneMachine(machine metav1.Object) bool {
 	return ok
 }
 
+// max calculates the maximum integer for two integer values.
+func max(valueOne, valueTwo int) int {
```
Comment (yastij) [inline pkg/util/machines.go:139]: we should use `k8s.io/utils/integer` instead of this

**Review by yastij — COMMENTED** [review]
/approve

File: pkg/util/machines.go (hunk 6 above)
Comment (srm09) [reply pkg/util/machines.go]: Didn't know this existed. Thanks!

**Review by srm09 — COMMENTED** [review]
Addressed the comments.

File: pkg/services/govmomi/service.go [hunk 7]
```diff
@@ -224,6 +224,15 @@ func (vms *VMService) reconcileMetadata(ctx *virtualMachineContext) (bool, error
 		return false, err
 	}
 
+	// checking if any of the network devices for the VSphereVM was removed
+	if statuses := len(ctx.State.Network); statuses > 0 {
+		if statuses > len(ctx.VSphereVM.Spec.Network.Devices) {
```
Comment (srm09) [inline pkg/services/govmomi/service.go:229]: The network statuses on the VM show the current number of devices attached whereas the `vm.spec.network.devices` holds the expected number of devices.
If a device is removed, the `statuses` list gets updated and will be lesser than the expected number of devices. Hence this condition should be flipped to
```golang
if statuses < len(ctx.VSphereVM.Spec.Network.Devices)
```

Also, have a question around, does it make sense to remove the check at line 228. Would that be necessary, or am I missing a case.

cc @yastij

Comment (yastij) [reply pkg/services/govmomi/service.go]: let's remove this check since folks are still managing network devices outside of CAPV.
