### PR TITLE
Fix reconcile of controlplane endpoint in VSphereCluster

### LINKED ISSUE #1020: Control plane endpoint in VSphereCluster overwritten by Cluster
/kind bug

**What steps did you take and what happened:**
 Launched a 3 master/3 worker cluster with static IP as the choice of IP allocation.

The kube-vip was not preconfigured in VSphereCluster( ControlPlaneEndpoint.Host = "", ControlPlaneEndpoint.Port= 6443 ). Instead, a third party IPAM controller set this IP when the VSphereCluster object was available.

Although this allocation went through, it was observed that this was immediately overwritten by an empty value.
This happens because of  https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspherecluster_controller.go#L472L479

The Controlplane endpoint from Cluster(Host="") is getting copied to VSphereCluster(Host="<allocated-ip>")

**What did you expect to happen:**
Expected VSphereCluster to be responsible for allocating controlplane endpoint. 
Is there a use-case where endpoint in Cluster overrides VSphereCluster ?

**Anything else you would like to add:**
Allocating all the IPs(VSphereMachine,HAProxyLB, kube-vip)  using a third party controller was required for static IP allocation.

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.0
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`):  CentOS 7

### PR DESCRIPTION
**Pull request by abhinavnagaraj**
**What this PR does / why we need it**:
1) Remove unwanted copying of controlplane endpoint from Cluster back to VSphereCluster.
2) Cleanup legacy code

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1020 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by yastij — APPROVED** [review]
/approve
/cc @gab-satchi

File: controllers/vspherecluster_controller.go [hunk 1]
```diff
@@ -274,11 +274,7 @@ func (r clusterReconciler) reconcileNormal(ctx *context.ClusterContext) (reconci
 	ctx.VSphereCluster.Status.Ready = true
 
 	// Reconcile the VSphereCluster resource's control plane endpoint.
-	if ok, err := r.reconcileControlPlaneEndpoint(ctx); !ok {
-		if err != nil {
-			return reconcile.Result{}, errors.Wrapf(err,
-				"unexpected error while reconciling control plane endpoint for %s", ctx)
-		}
+	if ok := r.reconcileControlPlaneEndpoint(ctx); !ok {
```
Comment (gab-satchi) [inline controllers/vspherecluster_controller.go:277]: This function and its logic is small enough that it can probably be inlined at this point: 
```
r.reconcileVSphereClusterWhenAPIServerIsOnline(ctx)
if ctx.VSphereCluster.Spec.ControlPlaneEndpoint.IsZero() {
  ctx.Logger.Info("control plane endpoint is not reconciled")
  return reconcile.Result{}, nil
}
```

Comment (abhinavnagaraj) [reply controllers/vspherecluster_controller.go]: Ack

**Comment by gab-satchi** [comment]
Getting a `"couldn't parse image name: repository name must be canonical"` but the images haven't been modified. 


/test pull-cluster-api-provider-vsphere-e2e

**Comment by gab-satchi** [comment]
thanks for the changes

/lgtm
