### PR TITLE
Fix govmomi actuator's Create when using clusterctl

### LINKED ISSUE #70: Bug: clusterctl create cluster fails with govmomi actuator
Using clusterctl, cluster creation always fails.  After some debugging, it appears kubeconfig cannot be pulled.  Root cause still unknown.

### PR DESCRIPTION
**Pull request by sflxn**
Clusterctl create cluster was not able to properly create the target cluster.  It would sit
in an infinite loop, attempting to clone the VM template.  The fix was to not use annotations
for task ref and vm ref during create.  Instead, use provider status.  Once this fix was in,
the Target cluster would then sit in an infinite loop, attempting to clone the VM template.
The fix was to check for nodeRef in the actuator's Exists() function.

In addition, moved utils from provisioner/common to provisioner/govmomi as it's only ever
used by the govmomi actuator.

Fixes #70

### CODE REVIEW

File: cloud/vsphere/provisioner/govmomi/create.go [hunk 1]
```diff
@@ -264,41 +268,72 @@ func (vc *Provisioner) removeTaskRef(machine *clusterv1.Machine) error {
...
+	}
+	return nil
 }
 
-// Sets the current task reference on the Machine object
-func (vc *Provisioner) setTaskRef(machine *clusterv1.Machine, taskref types.ManagedObjectReference) error {
-	nmachine := machine.DeepCopy()
-	if nmachine.ObjectMeta.Annotations == nil {
-		nmachine.ObjectMeta.Annotations = make(map[string]string)
+func (vc *Provisioner) setTaskRef(machine *clusterv1.Machine, taskref string) error {
```
[the remark this answers is not in the document]
Comment (sflxn) [reply cloud/vsphere/provisioner/govmomi/create.go]: not really.  most of the code is the same, but it modifies a different field.

[the remark this answers is not in the document]
Comment (figo) [reply cloud/vsphere/provisioner/govmomi/create.go]: you are right, one is updating`MachineRef `, and another is updating `TaskRef `, i think it make sense to has a common function to update ProviderStatus on different field.

File: cloud/vsphere/provisioner/govmomi/exists.go [hunk 2]
```diff
@@ -3,13 +3,19 @@ package govmomi
...
+	"github.com/golang/glog"
 	"github.com/vmware/govmomi/vim25/mo"
 	"github.com/vmware/govmomi/vim25/types"
 	vsphereutils "sigs.k8s.io/cluster-api-provider-vsphere/cloud/vsphere/utils"
 	clusterv1 "sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1"
 )
 
 func (vc *Provisioner) Exists(cluster *clusterv1.Cluster, machine *clusterv1.Machine) (bool, error) {
+	glog.Infof("govmomi.Actuator.Exists %s", machine.Spec.Name)
+	if machine.Status.NodeRef != nil {
```
Comment (sidharthsurana) [inline cloud/vsphere/provisioner/govmomi/exists.go]: I know you added this to resolve the issue with `clusterctl` CLI getting hung.. 
But IMHO in our provider's `Exists` method we should be truly checking the existence of the resource on the provider infrastructure and should be reporting on that. The `NodeRef` property is neither added nor controlled by the actuator, thus the actuator exists should not be using this check. 
As for the `clusterctl` CLI issue, I am still not sure how this check is helping, since the `NodeRef` does not get set until the pivot has happened, and the actuator's `Exists` method must have to return `true` for the master node before we could have ever triggered the pivot operation.
I think we should be fixing the code making up the `clusterctl` CLI that has logic making certain improper assumptions to begin with.

File: cloud/vsphere/provisioner/govmomi/update.go [hunk 3]
```diff
@@ -65,6 +68,7 @@ func (vc *Provisioner) updateIP(cluster *clusterv1.Cluster, machine *clusterv1.M
 	if nmachine.ObjectMeta.Annotations == nil {
 		nmachine.ObjectMeta.Annotations = make(map[string]string)
 	}
+	glog.Infof("updateIP - IP = %s", vmIP)
```
Comment (sidharthsurana) [inline cloud/vsphere/provisioner/govmomi/update.go]: switch to using `glog.V(4).Infof(...` so that we can selectively emit more or less logs

File: cloud/vsphere/provisioner/govmomi/update.go [hunk 4]
```diff
@@ -48,12 +50,13 @@ func (vc *Provisioner) Update(cluster *clusterv1.Cluster, machine *clusterv1.Mac
 	}
 
 	if _, err := vsphereutils.GetIP(cluster, machine); err != nil {
+		glog.Info("actuator.Update() - did not find IP, waiting on IP")
```
Comment (sidharthsurana) [inline cloud/vsphere/provisioner/govmomi/update.go]: switch to using `glog.V(4).Infof(...` so that we can selectively emit more or less logs

File: cloud/vsphere/provisioner/govmomi/utils.go [hunk 5]
```diff
@@ -1,4 +1,4 @@
-package common
```
Comment (sidharthsurana) [inline cloud/vsphere/provisioner/govmomi/utils.go]: The main reason I had it separate was if in future we have more that 1 actuator implementations (or `variants` implementations) then this would serve as the common code that could be reused across. Essentially terraform actuator could have used this as well but since we were going to remove that anyways, thus I did not make changes in that to use this common code.
Anyways, It's fine for now but later on we may still end up re-creating something like this again based on the different `variant` implementations.
